Lab1
PavloStr4620/LabJava pull request #1
Opened 2023-09-06 14:56 UTC by PavloStr4620

2023-09-12 14:13 UTC, RuslanSlobodian requested changes

2023-09-12 14:13 UTC, RuslanSlobodian commented on untitled/src/main/java/org/example/Formula.java
> +    private double x = 1.426, y = -1.220, z = 3.5;
Оголошуй атрибути в окремих рядках

2023-09-12 14:13 UTC, RuslanSlobodian commented on untitled/src/main/java/org/example/Formula.java
> +    public double firstSolution(){
Не інформативна назва методу, з неї не зрозуміти, що цей метод робить

2023-09-12 14:13 UTC, RuslanSlobodian commented on untitled/src/main/java/org/example/Formula.java
> +    public double secondSolution(){
Не інформативна назва методу, з неї не зрозуміти, що цей метод робить

2023-09-12 14:13 UTC, RuslanSlobodian commented on untitled/src/main/java/org/example/Formula.java
> +    public double firstSolution(double x, double y){
цей метод може бути статичним, оскільки не використовує атрибутів класу

2023-09-12 14:13 UTC, RuslanSlobodian commented on untitled/src/main/java/org/example/Formula.java
> +        return (2 * Math.cos(x - (Math.PI / 6))) / 0.5 + Math.pow(Math.sin(y), 2);
А ще тут дублується код з методу 
double firstSolution()

2023-09-12 14:13 UTC, RuslanSlobodian commented on untitled/src/main/java/org/example/Formula.java
> +        return (2 * Math.cos(x - (Math.PI / 6))) / 0.5 + Math.pow(Math.sin(y), 2);
Прибери дублювання коду

2023-09-12 14:13 UTC, RuslanSlobodian commented on untitled/src/main/java/org/example/Formula.java
> +        return 1 + ((Math.pow(z, 2)) / (3 + Math.pow(z, 2)) / 5);
Прибери дублювання коду

2023-09-12 14:13 UTC, RuslanSlobodian commented on untitled/src/main/java/org/example/Formula.java
> +        System.out.println("Дата: " + (date.getDay() + 3) + " " + (date.getMonth() + 1) + " " + (date.getYear() + 1900));
Вивід дати згідно певного шаблону виконувати за допомогою класу SimpleDateFormat, 
або методу System.out.pringf() вказавши необхідні специфікатори, які є описані в теоретичних відомостях

2023-09-30 09:01 UTC, PavloStr4620 commented
Виправив

2023-10-05 12:17 UTC, RuslanSlobodian approved these changes

2023-10-05 12:17 UTC, merged